layout_spectrum: 0.2070510471239686
typography_spectrum: 0.1254105200059712
color:
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  brandStrength: 0.01639608363620937
  lightness: 0.5090521203819662
  saturation: 0.14827024121768773
  rhythmicContrast: 0.4419020575005561
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Cars & Coffee Bergen
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Facebook
    url: 'https://www.facebook.com/groups/carsandcoffeebergen/'
    type: external
  - name: Cars & Coffee Bergen 10.april 2016
    id: 33f106d0-d619-43f4-9d5b-9320d234f17f
    type: content
favicon: null
title: '-der entusiaster møtes'
description: ''
purpose: []
