name: Cars & Coffee Bergen
favicon: null
layout_spectrum: 0.25161
typography_spectrum: 0.4395554030779749
navigation:
  - name: Facebook
    url: 'https://www.facebook.com/groups/carsandcoffeebergen/'
    type: external
  - name: Kjøp Cars & Coffe T-skjorter og krus
    url: 'http://shop.spreadshirt.no/carsandcoffeebergen/'
    type: external
title: '-der entusiaster møtes'
description: ''
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#3f3f3f'
    - '#c1c1c1'
    - '#bf2535'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
