layout_spectrum: 0.6856910288333893
typography_spectrum: 0.9293749141506851
color:
  brandStrength: 0.06962793553248048
  lightness: 0.3638466279953718
  saturation: 0.1593795963563025
  rhythmicContrast: 0.6863751753699034
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Cars & Coffee Bergen
navigation:
  - name: Facebook
    url: 'https://www.facebook.com/groups/carsandcoffeebergen/'
    type: external
  - name: Cars & Coffee Bergen 10.april 2016
    id: 33f106d0-d619-43f4-9d5b-9320d234f17f
    type: content
title: Cars & Coffee Bergen
description: '-der entusiaster møtes'
