typography_spectrum: 0.11404
color:
  brandColors:
    - '#fffeff'
    - '#222327'
    - '#ff6a8d'
    - '#ef253d'
    - '#b1b5b6'
  brandStrength: 0.06962793553248048
  lightness: 0.3638466279953718
  saturation: 0.1593795963563025
  rhythmicContrast: 0.6863751753699034
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Cars & Coffee Bergen
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Facebook
    url: 'https://www.facebook.com/groups/carsandcoffeebergen/'
    type: external
  - name: Cars & Coffee Bergen 10.april 2016
    id: 33f106d0-d619-43f4-9d5b-9320d234f17f
    type: content
favicon: null
title: '-der entusiaster møtes'
description: ''
purpose: []
